version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile    
    restart: always
    volumes:
      - ./src:/workspace
    networks:
        - app-network      

  web:
    image: nginx:1.18-alpine
    restart: always
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ./src:/workspace
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir:
      /workspace
    networks:
        - app-network      

  db:
    image: mysql:8.0
    container_name: alphatiles-db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db-store:/var/lib/mysql  
    networks:
        - app-network      

  dbtest:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testing_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    ports:
      - "3306:3306"
    volumes:
      - test-data:/var/lib/mysql
    networks:
      - laravel        

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: alphatiles_queue
    command: php /workspace/artisan queue:work --sleep=3 --tries=3 --timeout=90
    volumes:
      - ./src:/workspace
    networks:
        - app-network      
    
networks:
  app-network:
    driver: bridge

volumes:
  db-store:
  test-data:
