version: "3.8"
services:
  app:
    build: ./docker/php
    restart: always
    volumes:
      - ./src:/workspace

  web:
    image: nginx:1.18-alpine
    restart: always
    ports:
      - 8800:80
    volumes:
      - ./src:/workspace
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir:
      /workspace

  db:
    image: mysql:8.0
    container_name: alphatiles-db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db-store:/var/lib/mysql  

volumes:
  db-store:
